version: 2.1

executors:
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.60.0-noble

jobs:
  e2e-tests:
    executor: playwright

    steps:
      - checkout

      # Opcional: verificar versões
      - run:
          name: Verificando versões
          command: |
            node --version
            yarn --version

      # Instala dependências
      - run:
          name: Instalando dependências
          command: yarn

      # Instala browsers do Playwright
      # (na imagem oficial geralmente não é necessário,
      # mas pode manter se o projeto exigir)
      - run:
          name: Instalando Browsers do Playwright
          command: yarn playwright install

      # Executa os testes
      - run:
          name: Executando testes e2e
          command: yarn run e2e

      # Salva relatórios caso existam
      - store_artifacts:
          path: playwright-report

workflows:
  version: 2

  e2e-workflow:
    jobs:
      - e2e-tests