version: 2.1
orbs:
  node: circleci/node@5

jobs:
  e2e-tests:
    # Instala dependências, browsers do Playwright e executa os testes e2e
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install Playwright browsers
          command: yarn playwright install
      - run:
          name: Run e2e tests
          command: yarn run e2e

workflows:
  build-and-test:
    jobs:
      - e2e-tests