name: Execução Manual

on:
  workflow_dispatch:

jobs:

  jest:
    name: Jest Check
    runs-on: self-hosted

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando Jest e gerando relatório
        run: |
          mkdir -p test/components
          yarn test --json --outputFile=test/components/output.json

      - name: jest-check
        uses: soomo/jest-check@0.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEST_FOLDER: ${{ github.workspace }}/test/components

  e2e-tests:
    name: E2E Tests

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e